# Generated by Django 2.2.7 on 2019-11-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('post', models.TextField()),
            ],
        ),
    ]
